# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Release"
  lane :release do

    props = property_file_read(file: "app/version/version.properties")
    version = props["VERSION"]
    releaseNotes = File.read("../app/version/release-notes")
    apkPath = ENV["BITRISE_APK_PATH"]
    ENV["releaseNotes"] = releaseNotes

    UI.message ("Releasing new app version\nVersion: #{version}\nRelease Notes:\n=====\n#{releaseNotes}\n=====\n")

    uploadgithub(
        tag: version,
        releaseNotes: releaseNotes,
        apkPath: apkPath
    )
  end

  desc "Upload to GitHub releases"
  lane :uploadgithub do |values|

    version = values[:tag]
    releaseNotes = values[:releaseNotes]
    apkPath = values[:apkPath]
    token = ENV["GITHUB_UPLOAD_TOKEN"]
    UI.message("values: #{values}")

    UI.message("did the test work? " + ENV["releaseNotes"])

    UI.message ("Uploading #{version} APK to GitHub")

    set_github_release(
        repository_name: "CDRussell/Android",
        api_token: token,
        name: version,
        tag_name: version,
        description: releaseNotes,
        upload_assets: [apkPath],
        is_draft: false,
        is_prerelease: false
    )

  end

end
